#!/usr/bin/python2.6
import castle
import sys
import logging

def main(argv):
    #castle.pycastle_log.setLevel(logging.INFO)
    #castle.pycastle_log.setLevel(logging.DEBUG)

    micasa = castle.Castle()
    foo = micasa.collection_create("counters")

    #init the counter
    comp = 0;
    foo["bar"]=castle.CastleCounterAdd(0)
    for i in range(1, 6):
        c = pow(2, i)
        print "inserting ADD "+str(c)
        comp+=c
        foo["bar"]=castle.CastleCounterAdd(c)

    retval = castle.CastleCounter(foo["bar"]).value
    print "got "+str(retval)+", expecting "+str(comp)
    assert retval == comp, "wtf??"

if __name__ == '__main__':
    main(sys.argv[1:])
