#!/usr/bin/python2.6
import castle
import itertools
import logging
import sys

def main(argv):
    #castle.pycastle_log.setLevel(logging.INFO)
    castle.pycastle_log.setLevel(logging.DEBUG)

    #the ctor calls castle_connect and establishes shared buffers for keys and values
    micasa = castle.Castle()

    #make a new collection then attach to it
    foo = micasa.collection_create("test")

    foo["foo", "bar", "baz"] = "Hello World"

    #do a bunch of inserts on 3d keys
    for x, y, z in list(itertools.product(range(10,13), range(0,3), range(0,3))):
        foo[(str(x), str(y), str(z))] = str((x*1000 + y*100 + z*10)*2)

    expect_no_val = foo["this key doesn't exist"]
    if expect_no_val:
        raise Exception('baby got back (expected nothing, got something)')

    result=foo["foo", "bar", "baz"]
    print result
    assert result == "Hello World", "wtf?! result = "+str(result)

    #save the current version number
    i = foo.version_id
    print "We just saved the version number "+str(i)+" to a "+str(type(i))

    foo.snapshot()

    #get it all back from our 3d keys
    for x, y, z in list(itertools.product(range(10,13), range(0,3), range(0,3))):
        got_val = int(foo[(str(x), str(y), str(z))])
        print "got value "+str(got_val)
        expected_val = int(((x*1000 + y*100 + z*10)*2))
        assert expected_val == got_val, "expected "+str(expected_val)+", got "+str(got_val)

    foo["foo", "bar", "baz"] = "Hello World 2"
    result=foo["foo", "bar", "baz"]
    print result
    assert result == "Hello World 2", "wtf?! result = "+str(result)

    del foo["foo", "bar", "baz"]
    result=foo["foo", "bar", "baz"]
    assert not result, "wtf?! result = "+str(result)

    ##detach
    foo.detach()

    #attach to version i
    baz = micasa.collection_attach("baz", i)


    result = baz["foo", "bar", "baz"]
    print result
    assert result == "Hello World", "wtf?!"

    #this throws an exception because we can't handle non-string keys yet
    try:
        print baz["zero", 1]
    except Exception, e:
        print "EXCEPTION! "+str(e)
    #this throws an exception because we can't handle non-string values yet
    try:
        baz["1"] = 31
    except Exception, e:
        print "EXCEPTION! "+str(e)

    #dummy example of range query, just to illustrate the idea
    start_key = (str(0),str(0),str(0))
    stop_key = (str(2),str(2),str(2))
    baz_rq = baz[start_key:stop_key]
    print "Just made baz_rq, which is a "+str(type(baz_rq))
    print "next yielded "+str(baz_rq.next())
    print "next yielded "+str(baz_rq.next())
    for item in baz_rq:
        print "Got "+str(item)
        if item == 7:
            print "We found the item we were looking for; stopping range query"
            baz_rq.close()

    print "\nExiting test...\n"
    micasa.buffers_destroy()
    castle.ch.flush()
    print "Test complete."
    sys.exit(0)


if __name__ == '__main__':
    main(sys.argv[1:])

